# Shadowrocket: 2026-09-06 22:12:02
[General]
dns-server = 
private-ip-answer = false
prefer-ipv6 = true
update-url = https://raw.githubusercontent.com/Kyo628/ShadowRules/master/v6.conf
skip-proxy = 
tun-excluded-routes = 
always-real-ip = %INSERT%*.lan,cable.auth.com,*.msftconnecttest.com,*.msftncsi.com,*.*.*.srv.nintendo.net,*.*.stun.playstation.net,xbox.*.*.microsoft.com,*.*.xboxlive.com,stun.*,proxy.golang.org,*.icitymobile.mobi,pool.ntp.org,*.pool.ntp.org,ntp.*.com,time.*.com,ntp?.*.com,time?.*.com,time.*.gov,PDC._msDCS.*.*,DC._msDCS.*.*,GC._msDCS.*.*,www.googleapis.com
ipv6 = true

[Rule]
DOMAIN-SUFFIX,tiktok.com,REJECT-200
DOMAIN-SUFFIX,tiktokw.us,REJECT-200
DOMAIN-SUFFIX,unity3d.com,REJECT-200
DOMAIN-SUFFIX,vungle.com,REJECT-200
#DOMAIN-SUFFIX,app-analytics-services.com,YUEGAONEW
#DOMAIN-SUFFIX,legy-jp.line-apps.com,REJECT-NO-DROP
#DOMAIN-SUFFIX,ad.line-scdn.net,REJECT-DROP
FINAL,PROXY